#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

fakeFile = { 'firstname' : 'Jeff', 'lastname' : 'Johnson' }
r = requests.post(url, files=fakeFile)

print r.status_code
print r.text


